### ISSUE TITLE
Positive roots as a commutator

### ISSUE THREAD

**Issue by riteshksingh** [gutfeeling/K2P2#1]
**Speed Optimization request:**

A positive root can be written in two ways: 
(1) as a nested commutator of the simple root
(2)a commutator of simple root with another positive root lower in weight by one simple root. 

The latter representation require only one commutator calculation for each positive root higher than simple root and best suited for computation. We should change the positive root representation to the second type.

**Comment by gutfeeling** [comment]
Resolved in 659904e45a619e9b9d87b7274ba1e0959ff47ba4
