### ISSUE TITLE
Representation Matrix as a Sparse Matrix

### ISSUE THREAD

**Issue by riteshksingh** [gutfeeling/K2P2#2]
**Speed+Memory Optimization**

The representation matrices for the roots are usually very sparse. Thus it makes more sense to use one of the standard _sparse-matrix representation_ to store these matrices. This reduces the memory needed to store these representation matrices and also speedup the matrix multiplication required for computation of commutators.

**Comment by gutfeeling** [comment]
Resolved in 8a1e343ce8a389769ab48035a380f5089f7157fb
