### ISSUE TITLE
Speed up scalar product computations

### ISSUE THREAD

**Issue by gutfeeling** [gutfeeling/K2P2#4]
Computing the scalar product for the state given by the lowering chain [2, 3, 5, 4, 6, 3, 4, 2, 3, 1, 0, 2, 1, 5, 3, 4, 2, 3, 5, 6, 4, 3, 2, 1, 0] in the E7 representation [0,0,0,0,0,0,1] takes more than a full minute. This function needs to be optimized somehow.

**Comment by riteshksingh** [comment]
Using Dynkin labels for weights and simple roots (in place of explicit forms) requires one to perform arithmetic with  integers only (in place of surd of rational numbers). The integer arithmetic operations are very fast and can improve the performance of scalar_product routine.

**Comment by gutfeeling** [comment]
Fixed in master branch.
